[package]
name = "externref-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
walrus = "0.19.0"

externref = { version = "0.1.0", path = "../..", default-features = false }
