name: Build

on:
  workflow_call:
    inputs:
      rust_version:
        type: string
        description: Rust version to use in the build
        required: false
        default: stable

env:
  binaryen: version_110

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust_version }}
          targets: wasm32-unknown-unknown
          components: rustfmt, clippy
      - name: Install wasm-opt
        run: |
          wget -q -O binaryen.tar.gz https://github.com/WebAssembly/binaryen/releases/download/$binaryen/binaryen-$binaryen-x86_64-linux.tar.gz && \
          tar xf binaryen.tar.gz && \
          sudo install "binaryen-$binaryen/bin/wasm-opt" /usr/local/bin
      - name: Install cargo-deny
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-deny
          version: "^0.16"

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo

      - name: Format
        run: cargo fmt --all -- --check --config imports_granularity=Crate --config group_imports=StdExternalCrate

      - name: Clippy
        run: cargo clippy --workspace --all-features --all-targets -- -D warnings
      - name: Clippy (no features)
        run: cargo clippy -p externref --no-default-features --lib -- -D warnings
      - name: Clippy (processor)
        run: cargo clippy -p externref --no-default-features --features=processor --lib -- -D warnings

      - name: Check dependencies
        run: cargo deny --all-features check

      # Build the E2E crate first to speed up its testing.
      - name: Build E2E test crate
        run: cargo build -p externref-test --lib --target wasm32-unknown-unknown --profile wasm

      - name: Run tests
        run: cargo test --workspace --all-features --all-targets
      - name: Run doc tests
        run: cargo test --workspace --all-features --doc
